{% set name = "mongoquery" %}
{% set version = "1.3.6" %}
{% set sha256 = "595d4c347d9da022c8f518c700b116f3f9b018e5dbdaa8b21b0d6c080a7cdb54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - mongoquery

about:
  home: https://github.com/kapouille/mongoquery
  license: Public Domain
  license_file: LICENSE
  summary: A utility library that provides a MongoDB-like query language for querying python collections. It is mainly intended to parse objects structured as fundamental types in a similar fashion to what is produced by JSON or YAML parsers.
