{% set name = "mongoquery" %}
{% set version = "1.1.0" %}
{% set sha256 = "d1e87f6038ea074273610b6258e5af7477de61c782f6424fc7ecf3416df3e645" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kapouille/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - mongoquery

about:
  home: https://github.com/kapouille/mongoquery
  license: Public Domain
  summary: >
    A utility library that provides a MongoDB-like query
    language for querying python collections. It's mainly
    intended to parse objects structured as fundamental types in
    a similar fashion to what is produced by JSON or YAML
    parsers.
